image: Ubuntu

stack: jdk 11

build: off

install:
  - chmod +x ./gradlew
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose -f ./docker-compose.yml up --build -d
  - sleep 60
  - sudo java -Dspring.datasource.url=jdbc:postgresql://localhost:5432/app -Dspring.datasource.username=app -Dspring.datasource.password=pass -jar ./artifacts/aqa-shop.jar &
  - sleep 30
  - sudo curl localhost:8080
build_script:
  - ./gradlew -Ddb.url=jdbc:postgresql://localhost:5432/app -Ddb.user=app -Ddb.password=pass clean test -Dselenide.headless=true