name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: docker-compose up
        run: docker-compose -f ./docker-compose.yml up --build -d
      - name: sleep
        run: sleep 60
      - name: java run
        run: sudo java -jar ./artifacts/aqa-shop.jar &
      - name: sleep
        run: sleep 30
      - name: curl
        run: sudo curl localhost:8080
      - name: gradlew test
        run: ./gradlew test -Dselenide.headless=true